package com.example.delivary_user_android.common.domain.exceptions

enum class RequestErrorKeyValues {
    PASSWORD_LENGTH_BETWEEN_8_15,
    PHONE_NUMBER_BETWEEN_9_15,
    PHONE_COUNTRY_CODE_NOT_EMPTY,
    USER_FIRST_NAME_BETWEEN_3_15,
    USER_LAST_NAME_BETWEEN_3_15,
    USER_EMAIL_FORMAT,
    USER_MIDDLE_NAME_LESS_THAN_15,
    BIRTH_DATE_SHOULD_BE_LESS_THAN_13_YEARS,
    IMAGE_MIME_JPG_JPEG_PNG_AND_MAX_SIZE_512KB
}